name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter test --coverage
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: coverage/lcov.info

  upload:
    runs-on: ubuntu-22.04
    needs: [collect]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
