name: Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  id-token: write

jobs:
  pub-dev:
    if: |
      ${{github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'autorelease: pending')}}
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub publish --force
